### PR TITLE
Experimental support for markdown

### PR DESCRIPTION
**Pull request by dsego**
Issue #1 

screen shot 2017-03-14 at 3 51 19 am

### CODE REVIEW

**Comment by zenorocha** [comment]
Hey @dsego, sorry for taking so long to merge. I tried to fetch your commit but I couldn't because the repository was deleted. I added manually and mentioned you: https://github.com/dracula/sublime/commit/dc87891be8e292f0fa62aaff809d146a38acb93f

Thanks a lot for contributing!

**Comment by dsego** [comment]
@zenorocha Sorry for deleting my fork, I wasn't sure if this was good enough and had some other ideas. But thanks for including it, glad it works.

**Comment by zenorocha** [comment]
No problem, thank you again!

**Comment by zenorocha** [comment]
And feel free to share any ideas that you might have ;)

**Pull request closed without merging**
